-- Organization and user profile fields for sign-in setup
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "registrationId" TEXT;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "contactEmail" TEXT;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "country" TEXT NOT NULL DEFAULT 'IN';
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'INR';
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 18;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "unitSystem" TEXT NOT NULL DEFAULT 'metric';
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "precision" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "isStandardsDefault" TEXT DEFAULT 'IS 456:2000';
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "setupComplete" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "jobTitle" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
