import puppeteer from "puppeteer";
import { requirePrisma } from "../db.js";

export interface BoqPdfData {
  projectName: string;
  clientName: string;
  version: number;
  label: string | null;
  lines: {
    itemNo: string;
    description: string;
    unit: string;
    quantity: number;
    rate: number;
    amount: number;
  }[];
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function formatCurrency(n: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 2,
  }).format(n);
}

function generateBoqHtml(data: BoqPdfData): string {
  const subtotal = data.lines.reduce((sum, l) => sum + l.amount, 0);
  const contingency = subtotal * 0.05;
  const tax = subtotal * 0.15;
  const grandTotal = subtotal + contingency + tax;

  const rows = data.lines
    .map(
      (l) => `<tr>
        <td style="border:1px solid #2A3441;padding:6px 10px;">${escapeHtml(l.itemNo)}</td>
        <td style="border:1px solid #2A3441;padding:6px 10px;">${escapeHtml(l.description)}</td>
        <td style="border:1px solid #2A3441;padding:6px 10px;text-align:center;">${escapeHtml(l.unit)}</td>
        <td style="border:1px solid #2A3441;padding:6px 10px;text-align:right;">${l.quantity.toFixed(2)}</td>
        <td style="border:1px solid #2A3441;padding:6px 10px;text-align:right;">${formatCurrency(l.rate)}</td>
        <td style="border:1px solid #2A3441;padding:6px 10px;text-align:right;">${formatCurrency(l.amount)}</td>
      </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>BOQ v${data.version}</title>
  <style>
    body { font-family: 'Inter', sans-serif; background: #0B0F14; color: #F8FAFC; margin: 0; padding: 40px; }
    h1 { font-size: 24px; font-weight: 700; margin-bottom: 8px; }
    h2 { font-size: 16px; font-weight: 600; color: #94A3B8; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { background: #1A2230; color: #94A3B8; font-weight: 600; text-align: left; padding: 8px 10px; border: 1px solid #2A3441; }
    td { color: #F8FAFC; }
    .summary { margin-top: 24px; width: 100%; max-width: 400px; margin-left: auto; }
    .summary-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #2A3441; }
    .summary-row.total { font-size: 18px; font-weight: 700; color: #3B82F6; border-top: 2px solid #3B82F6; margin-top: 8px; padding-top: 12px; }
    .footer { margin-top: 40px; font-size: 11px; color: #64748B; text-align: center; }
  </style>
</head>
<body>
  <h1>Bill of Quantities</h1>
  <h2>${escapeHtml(data.projectName)} — ${escapeHtml(data.clientName || "Client")} — v${data.version}${data.label ? ` (${escapeHtml(data.label)})` : ""}</h2>
  <table>
    <thead>
      <tr>
        <th>Item #</th>
        <th>Description</th>
        <th>Unit</th>
        <th style="text-align:right;">Qty</th>
        <th style="text-align:right;">Rate</th>
        <th style="text-align:right;">Amount</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="summary">
    <div class="summary-row"><span>Subtotal</span><span>${formatCurrency(subtotal)}</span></div>
    <div class="summary-row"><span>Contingency (5%)</span><span>${formatCurrency(contingency)}</span></div>
    <div class="summary-row"><span>GST / Tax (15%)</span><span>${formatCurrency(tax)}</span></div>
    <div class="summary-row total"><span>Grand Total</span><span>${formatCurrency(grandTotal)}</span></div>
  </div>
  <div class="footer">
    Generated by Civil Est Pro — ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`;
}

/**
 * Generate a real PDF from BOQ data using Puppeteer.
 * Falls back to HTML if Puppeteer is unavailable.
 */
export async function generateBoqPdf(data: BoqPdfData): Promise<{
  pdf: Buffer;
  contentType: string;
  filename: string;
}> {
  try {
    const browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });
    const page = await browser.newPage();
    const html = generateBoqHtml(data);
    await page.setContent(html, { waitUntil: "load" as const });
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "20mm", right: "20mm", bottom: "20mm", left: "20mm" },
    });
    await browser.close();
    return {
      pdf: Buffer.from(pdf),
      contentType: "application/pdf",
      filename: `boq-v${data.version}-${Date.now()}.pdf`,
    };
  } catch (err) {
    console.error("[PDF] Puppeteer failed:", err);
    throw new Error("PDF generation failed. Please ensure Puppeteer is properly installed.");
  }
}

/**
 * Generate PDF from a BOQ version stored in the database.
 */
export async function generateBoqPdfFromVersion(
  versionId: string
): Promise<{ pdf: Buffer; contentType: string; filename: string }> {
  const prisma = requirePrisma();
  const version = await prisma.boqVersion.findFirst({
    where: { id: versionId },
    include: { lines: true, project: true },
  });

  if (!version) {
    throw new Error("BOQ version not found");
  }

  return generateBoqPdf({
    projectName: version.project.name,
    clientName: version.project.clientName || "",
    version: version.version,
    label: version.label,
    lines: version.lines.map((l) => ({
      itemNo: l.itemNo,
      description: l.description,
      unit: l.unit,
      quantity: Number(l.quantity),
      rate: Number(l.rate),
      amount: Number(l.amount),
    })),
  });
}
